#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Trafficount.Resource", IsApplication=true)]

namespace Trafficount
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AppIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_left_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arrow_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int arrow_right_up = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int arrow_up = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int done = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int edit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int export = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int modal_bike = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int modal_bus = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int modal_car = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int modal_motorcycle = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int modal_truck = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ped_cross = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ped_run = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int remove = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int settings = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int timer = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int timer_off = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int ButtonUpdate = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int GridItems = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int LayoutAbout = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int ListCorners = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int TextDetails = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int TextEmpty = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int TextKey = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int TextKeyLabel = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int TextName = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int TextVersion = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int itemHeader = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int itemImage = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int itemSubtle = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int itemText = 2131099652;
			
			// aapt resource value: 0x7f060013
			public const int menuAdd = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int menuDone = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int menuEdit = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int menuExport = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int menuRemove = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int menuSettings = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int menuStartTimer = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int menuStopTimer = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Counting = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GridItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int CountingMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int DetailsMenu = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MainMenu = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SettingsMenu = 2131034115;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AppAuthor = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int AppLicense = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int AppName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AppOwner = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AppVerion = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int about = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int activation = 2130968583;
			
			// aapt resource value: 0x7f040014
			public const int add = 2130968596;
			
			// aapt resource value: 0x7f04001c
			public const int appActivated = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int appNotActivated = 2130968603;
			
			// aapt resource value: 0x7f04000f
			public const int description = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int details = 2130968581;
			
			// aapt resource value: 0x7f040016
			public const int done = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int edit = 2130968599;
			
			// aapt resource value: 0x7f040024
			public const int emailChoose = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int emailSubject = 2130968611;
			
			// aapt resource value: 0x7f04000d
			public const int empty = 2130968589;
			
			// aapt resource value: 0x7f040015
			public const int export = 2130968597;
			
			// aapt resource value: 0x7f04000a
			public const int goodThru = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int insertKey = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int name = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int no = 2130968595;
			
			// aapt resource value: 0x7f04001e
			public const int noFile = 2130968606;
			
			// aapt resource value: 0x7f040018
			public const int remove = 2130968600;
			
			// aapt resource value: 0x7f040010
			public const int removeConfirm = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int removeMessage = 2130968593;
			
			// aapt resource value: 0x7f040021
			public const int removed = 2130968609;
			
			// aapt resource value: 0x7f040006
			public const int settings = 2130968582;
			
			// aapt resource value: 0x7f040019
			public const int startTimer = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int stopTimer = 2130968602;
			
			// aapt resource value: 0x7f040022
			public const int timerOver = 2130968610;
			
			// aapt resource value: 0x7f04000c
			public const int updateKey = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int validate = 2130968587;
			
			// aapt resource value: 0x7f040020
			public const int warningDuplicate = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int warningNull = 2130968607;
			
			// aapt resource value: 0x7f04001d
			public const int wrongKey = 2130968605;
			
			// aapt resource value: 0x7f040012
			public const int yes = 2130968594;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
